# 使用基础Python镜像
FROM python:3.11-slim

# 设置工作目录
WORKDIR /app

# 将requirements.txt复制到容器
COPY data/private_syn/docker_requirements.txt /app/

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt

# 复制项目代码到容器
COPY data/private_syn /app/data/private_syn
